### ISSUE TITLE
hl folder and streams are not live

### ISSUE THREAD

**Issue by nafatrue** [theraw/FOS-Streaming-v69#2]
streams are working no freezes no problem but only one issue, sorry i find that when i replay a channel the stream is not live only streaming files from hl folder when i remove those files and restart server i start have live stream again, you can say that every channel i pick to play start streaming from the moment i started it on the server

**Comment by theraw** [comment]
FOS streaming simply restreams so if stream link on FOS is offline it also means that your backend/source is offline the generated video segments `(.ts)` and playlist `(.m3u8)` which are stored on `hl` folder will get played when you try to play that stream but your backend link is offline/broken, this content stored on `hl` folder will get removed only if you click "stop" stream from panel as admin.

However as you can see nothing is changed on project just some stuff about nginx and installation method so this is a fork of https://github.com/zgelici/FOS-Streaming-v1 and for code or problems you should talk with zgelici

FOS panel is just a restream creates you a chance to re stream same links and sell them for multiple user, however you you could very simply reach this by using nginx-rtmp module and nginx-authorization FOS-streaming uses PHP to re-stream and PHP takes more resources then simply using nginx that's why i don't want to try and release a better version of FOS when you could simply create a new and better one!

**Comment by nafatrue** [comment]
thanks for the reply i'm not selling anything i'm just trying to learn new things and iptv come in my way the panel you enhanced is cool i saw the old one, yours is more easy to install with the script you provided i found fastocloud more robust i'm trying now to install it even it is very frustrating

**Comment by theraw** [comment]
well i just explained how many IPTV panels work.

Never tried fastocloud, i took a look at their github repo their WIKI is totally wrongly explained clearly to sell their PRO version so gl with that.
