### ISSUE TITLE
Technical improvement request

### ISSUE THREAD

**Issue by Marthinius** [theraw/FOS-Streaming-v69#4]
Hi,
I know you're not an author, but I still want to **thank you** for it.
I have a technical problem.

"When I add and start several streams (e.g. 4 streams), the same number of ffmpeg process start automatically (4 ffmpeg process) without playing a playlist.
With a larger amount of stream the processor is heavy loaded.

When I tried it in tvheadend only the current strream opens the ffmpeg process (m3u playlist: 1 stream play = 1 ffmpeg process)

Is it possible to modify the "functions.php" script to run only 1 ffmpeg process at the request of the playlist m3u ? 

actual ffmpeg process example (no channel play over .m3u list) : 

![ffmpeg](https://user-images.githubusercontent.com/35543561/93088706-8ed5e380-f69a-11ea-9f40-e6ea52e7cc19.PNG)

**Comment by theraw** [comment]
don't understand how else would you re'stream a link without using a ffmpeg proccess for each stream STARTED on panel?

I'm open to suggestions!

**Comment by Marthinius** [comment]
I expressed myself in a wrong way.
FFmpeg is needed, but only on request.
For example: 
I select and run channel 1 in vlc.
The Fos panel receives a request for channel 1 and runs ffmpeg for this channel.

Unfortunely, now ffmpeg will run automatically for all channels that have been added.(previous picture)

**Comment by theraw** [comment]
i understand what you want but using transcode profile copy/copy should not use more then 0.1-1% of your resources for each stream,

Don't do encoding on stream server, ffmpeg will simply eat all your cpu for single channel
![image](https://user-images.githubusercontent.com/32969774/93142450-4fcd7f80-f6e6-11ea-9a7e-d2b5adc3cdd0.png)

so the way how fos streaming keeps all time active one ffmpeg proccess when you use transcode copy is not a problem as only 0.1% or 1% *(on a 4vCore @2.7Ghz)* of your resources would be used is only copy no cpu usage for encoding... 
![image](https://user-images.githubusercontent.com/32969774/93144197-c3bd5700-f6e9-11ea-9b77-5426f5370739.png)


Is better to let it like this, what you're suggesting is nice but this
> The Fos panel receives a request for channel 1 and runs ffmpeg for this channel.

this way will create a new ffmpeg proccess for every new user that opens stream link

and if you decide to share session things get even more complicated you will have to create a session when first user open stream link and share same session with other users, and keep track of each link when viewers are online/offline in order to start/stop your ffmpeg proccess, so is not worth your time to code because transcoder copy will still use low resources and if you use your fos streaming server for encoder resources will be used fully as you can see on first screenshot.

At last as far as i can see this is what i think

**Comment by Marthinius** [comment]
Yeah, you are right. Thank you for your help.
