### ISSUE TITLE
Technical improvement request

### ISSUE THREAD

**Issue by Marthinius** [theraw/FOS-Streaming-v69#5]
Hi,

Is it possible to modify the "functions.php" script to add encryption HLS supports AES-128 ?
This is a guide, how to add encryption: https://hlsbook.net/how-to-encrypt-hls-video-with-ffmpeg/

thanks for the effort

**Comment by theraw** [comment]
yeah well it looks simple but its not that simple, as it will require to rewrite whole channel list providing method of fos-streaming because when you download the m3u playlist from https://github.com/theraw/FOS-Streaming-v69/blob/master/getfile.php#L32-L50 it will be a list like
```
#EXTM3U 
#EXTINF:0,channel name
http://172.18.0.2:8000/live/username/username/1
```
this means that your channel is `http://172.18.0.2:8000/live/username/username/1` now you need to find where this url sends you which is here https://github.com/theraw/FOS-Streaming-v69/blob/master/functions.php#L292 `(stream.php)`
and now `stream.php` provides the stream output directly and not in segments or the m3u8 playlist wich is generated from ffmpeg it just packs up all the segments and sends it to the channel url `http://172.18.0.2:8000/live/username/username/1` 
```bash
root@dope:~# curl http://172.18.0.2:8000/live/theraw/theraw/1
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
```
which mean if you want to add AES encryption u'll have to change this whole proccess.
Sorry but this simple thing is not as simple as it looks it requires to re'do lots of stuff...


if you think that doing 
```
#EXTM3U 
#EXT-X-KEY:METHOD=AES-128,URI="https://domain.com/enc.key",IV=0x772f369373cb59829619ac41e8aa4bad
#EXTINF:0,channel name
http://172.18.0.2:8000/live/username/username/1
#EXTINF:0,channel name2
http://172.18.0.2:8000/live/username/username/2
```
this way it doesn't work :confused:
