### ISSUE TITLE
The installation was successful but the m3u file can't be played

### ISSUE THREAD

**Issue by zekripedia** [theraw/FOS-Streaming-v69#9]
I have completed the installation properly with no errors, I have also imported the playlist and started the stream, but when I download the m3u file from the user page, none of the URLs can be accessed while the m3u source can be accessed properly.

**Comment by theraw** [comment]
before publishing i tested the script and it was working, but since i had no list to import i have not tested the "import" option well.

However make sure that the imported urls are all working and supported and set properly if you somehow can't see if links are set properly from panel open phpmyadmin on your server and check out. Keep in mind that not every type of link is supported so make sure they work with fos-streaming by testing one solo then go for import.
